# Generated by Django 3.2.16 on 2023-01-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230124_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image_url',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
